"""migration tables

Revision ID: 98895b578f49
Revises: 1440f37d64a9
Create Date: 2025-01-30 19:39:36.671507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98895b578f49'
down_revision = '1440f37d64a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercadorias',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nro_registro', sa.String(length=50), nullable=False),
    sa.Column('fabricante', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('mercadoria_nome', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mercadoria_nome'], ['mercadorias.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('mercadoria_nome', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mercadoria_nome'], ['mercadorias.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('saidas')
    op.drop_table('entradas')
    op.drop_table('users')
    op.drop_table('mercadorias')
    # ### end Alembic commands ###
